config/routes.rb
Rails.application.routes.draw do
  root 'book_editions#index'

  resources :book_editions, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_edition.rb
class BookEdition < ApplicationRecord
  enum edition: %i[
    reprint
    slp
    special
    rehearsal
    script_ed
    anniversary
    reissue
    unabridged
  ]
  enum binding: %i[hardcover paper_bound vhs laser_disc ebook]
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  enum role: %i[reader librarian administrator]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_editions_controller.rb
class BookEditionsController < ApplicationController
  before_action :find_book_edition, only: [:show]

  def index
    @book_editions = BookEdition.order(:id).page(params[:page])
  end

  def show; end

  def new
    @book_edition = BookEdition.new
  end

  private

  def find_book_edition
    @book_edition = BookEdition.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/book_editions/index.html.erb
<h1>Listing Book Editions</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>ISBN-13</th>
      <th>Link</th>
    </tr>
  </thead>
  <tbody>
    <% @book_editions.each do |book_edition| %>
      <tr>
        <td><%= book_edition.title %></td>
        <td><%= book_edition.isbn13 %></td>
        <td><%= link_to 'Show', book_edition %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @book_editions %>
<%= link_to 'New Book Edition', new_book_edition_path %>

app/views/book_editions/new.html.erb
<h1>New Book Eidition</h1>

<%= simple_form_for @book_edition do |f| %>
  <%= f.input :title %>
  <%= f.input :isbn10 %>
  <%= f.input :isbn13 %>
  <%= f.input :edition, as: :radio_buttons, collection: BookEdition.editions.to_a.map { |item| item[0].humanize } %>
  <%= f.button :submit %>
<% end %>

app/views/book_editions/show.html.erb
<h1>Book Edition Information</h1>
<p><b>Title: </b><%= @book_edition.title %></p>
<p><b>ISBN-10: </b> <%= @book_edition.isbn10 %></p>
<p><b>ISBN-13: </b> <%= @book_edition.isbn13 %></p>
<p><b>Edition: </b> <%= @book_edition.edition.humanize %></p>
<p><b>Binding: </b> <%= @book_edition.binding.humanize %></p>
<p><b>Author: </b> <%= @book_edition.author %></p>
<p><b>Sizes: </b> <%= @book_edition.width %> width, <%= @book_edition.height %> height, <%= @book_edition.depth %> depth</p>
<p><b>Description: </b> <%= @book_edition.description %></p>
<p><b>Publish Date: </b> <%= t @book_edition.publish_date %></p>
<p><b>Removed: </b> <%= t @book_edition.removed %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayEthereumWithRuby</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Ethereum with Ruby', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Book Editions', book_editions_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Books', '#', class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>